spring:
  application:
    name: product-service

  datasource:
    url: jdbc:postgresql://localhost:5432/product_service
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 7001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
